name: Publish Action
on:
  push:
    branches: [ master ]

jobs:
  publish:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:

    - name: clone
      uses: actions/checkout@master

    - name: build
      env:
        GOOS: linux
        CGO_ENABLED: '0'
      run: go build -a -ldflags '-s -w -extldflags "-static"' -o release/vela-server github.com/go-vela/server/cmd/server

    - name: publish
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: target/vela-git
        cache: true
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
